// ============================================================================
// glycemic.js — Base d'INDEX GLYCÉMIQUE (IG) des aliments.
// Données extraites des documents fournis (tables d'index glycémique).
// Catégories : IG bas < 40 · IG moyen 40–59 · IG élevé ≥ 60.
// Plus l'IG est bas, plus la glycémie monte lentement (utile en perte de poids).
// ============================================================================

export const GI_FOODS = [
  { n: "Abricot (boîte, au sirop)", ig: 60 },
  { n: "Abricot (fruit frais)", ig: 30 },
  { n: "Abricot sec", ig: 35 },
  { n: "Agave (sirop)", ig: 15 },
  { n: "Ail", ig: 30 },
  { n: "Airelle rouge / canneberge [Jus de] (sans sucre)", ig: 50 },
  { n: "Airelle rouge, canneberge", ig: 45 },
  { n: "Airelle, myrtille", ig: 25 },
  { n: "All Bran", ig: 50 },
  { n: "Amande", ig: 15 },
  { n: "Amarante", ig: 35 },
  { n: "Amarante soufflée", ig: 70 },
  { n: "Amidons modifiés", ig: 100 },
  { n: "Ananas (boîte)", ig: 65 },
  { n: "Ananas (fruit frais)", ig: 45 },
  { n: "Ananas [Jus de] (sans sucre)", ig: 50 },
  { n: "Anone chérimole, anone écailleuse, pomme cannelle, corossol", ig: 35 },
  { n: "Arro-wroot, herbe aux flèches", ig: 85 },
  { n: "Artichaut", ig: 20 },
  { n: "Asperge", ig: 15 },
  { n: "Aubergine", ig: 20 },
  { n: "Avocat", ig: 10 },
  { n: "Avoine", ig: 40 },
  { n: "Bagels", ig: 70 },
  { n: "Baguette, pain blanc", ig: 70 },
  { n: "Baies de Goji", ig: 25 },
  { n: "Banane (mûre)", ig: 60 },
  { n: "Banane (verte)", ig: 45 },
  { n: "Banane plantain (crue)", ig: 45 },
  { n: "Banane plantain (cuite)", ig: 70 },
  { n: "Barre énergétique de céréale (sans sucre)", ig: 50 },
  { n: "Barres chocolatées (sucrées)", ig: 70 },
  { n: "Betterave (crue)", ig: 30 },
  { n: "Betterave (cuite)", ig: 65 },
  { n: "Beurre de cacahuète (sans sucre ajouté)", ig: 40 },
  { n: "Biscotte", ig: 70 },
  { n: "Biscuit", ig: 70 },
  { n: "Biscuit (farine complète, sans sucre)", ig: 50 },
  { n: "Biscuit sablé (farine, beurre, sucre)", ig: 55 },
  { n: "Bière", ig: 110 },
  { n: "Blette, bette", ig: 15 },
  { n: "Blé (type Ebly)", ig: 45 },
  { n: "Bouillie de farine de maïs", ig: 70 },
  { n: "Boulgour, bulgur (blé, cuit)", ig: 55 },
  { n: "Boulgour, bulgur complet (blé, cuit)", ig: 45 },
  { n: "Brioche", ig: 70 },
  { n: "Brocoli", ig: 15 },
  { n: "Brugnons, nectarines (blancs ou jaunes; fruit frais)", ig: 35 },
  { n: "Cacahuètes, arachides", ig: 15 },
  { n: "Cacao en poudre (sans sucre)", ig: 20 },
  { n: "Canne à sucre séché  [Jus de]", ig: 65 },
  { n: "Capellini", ig: 45 },
  { n: "Carottes (crues)", ig: 30 },
  { n: "Carottes (cuites)", ig: 85 },
  { n: "Carottes [Jus de] (sans sucre)", ig: 40 },
  { n: "Cassoulet", ig: 35 },
  { n: "Cerises", ig: 25 },
  { n: "Cerises des antilles, acérola", ig: 20 },
  { n: "Champignon", ig: 15 },
  { n: "Chayotte, christophine (purée de)", ig: 50 },
  { n: "Chicorée (boisson)", ig: 40 },
  { n: "Chips", ig: 70 },
  { n: "Chocolat noir (>70% de cacao)", ig: 25 },
  { n: "Chocolat noir (>85% de cacao)", ig: 20 },
  { n: "Chou-fleur", ig: 15 },
  { n: "Choucroute", ig: 15 },
  { n: "Choux", ig: 15 },
  { n: "Choux de Bruxelles", ig: 15 },
  { n: "Châtaigne, marron", ig: 60 },
  { n: "Cidre brut", ig: 40 },
  { n: "Citron", ig: 20 },
  { n: "Citron [Jus de] (sans sucre)", ig: 20 },
  { n: "Coing (fruit frais)", ig: 35 },
  { n: "Colas, boissons gazeuses, sodas (type Coca-Cola®)", ig: 70 },
  { n: "Concombre", ig: 15 },
  { n: "Confiture (marmelade) sans sucre (jus de raisin concentré)", ig: 45 },
  { n: "Confiture standard (sucrée)", ig: 65 },
  { n: "Corn Flakes, flocons de mais", ig: 85 },
  { n: "Cornichon", ig: 15 },
  { n: "Courges (diverses)", ig: 75 },
  { n: "Courgettes", ig: 15 },
  { n: "Couscous intégral, semoule integrale", ig: 45 },
  { n: "Couscous semoule complète", ig: 50 },
  { n: "Couscous, semoule", ig: 65 },
  { n: "Croissant", ig: 70 },
  { n: "Crème glacée (au fructose)", ig: 35 },
  { n: "Crème glacée classique (sucrée)", ig: 60 },
  { n: "Céleri branches", ig: 15 },
  { n: "Céleri rave (cru; rémoulade)", ig: 35 },
  { n: "Céleri rave (cuit)", ig: 85 },
  { n: "Céréales complètes (sans sucre)", ig: 45 },
  { n: "Céréales germées (germes de blé, de soja...)", ig: 15 },
  { n: "Céréales raffinées sucrées", ig: 70 },
  { n: "Cœur de palmier", ig: 20 },
  { n: "Dattes", ig: 70 },
  { n: "Doughnuts", ig: 75 },
  { n: "Echalote", ig: 15 },
  { n: "Endives, chicorée", ig: 15 },
  { n: "Epinards", ig: 15 },
  { n: "Falafel (fèves)", ig: 40 },
  { n: "Falafel (pois chiches)", ig: 35 },
  { n: "Farine d'amande", ig: 20 },
  { n: "Farine d'amarante", ig: 40 },
  { n: "Farine d'orge mondé", ig: 30 },
  { n: "Farine d'épeautre (intégrale)", ig: 45 },
  { n: "Farine d'épeautre (raffinée)", ig: 65 },
  { n: "Farine de blé (blanche)", ig: 85 },
  { n: "Farine de blé (complète)", ig: 60 },
  { n: "Farine de blé (intégrale)", ig: 45 },
  { n: "Farine de blé (semi complète)", ig: 65 },
  { n: "Farine de blé blanche", ig: 85 },
  { n: "Farine de blé complète", ig: 60 },
  { n: "Farine de châtaigne", ig: 65 },
  { n: "Farine de coco", ig: 35 },
  { n: "Farine de farro (intégrale)", ig: 45 },
  { n: "Farine de fonio", ig: 55 },
  { n: "Farine de kamut (intégrale)", ig: 45 },
  { n: "Farine de lentille", ig: 35 },
  { n: "Farine de lupin", ig: 15 },
  { n: "Farine de maïs", ig: 70 },
  { n: "Farine de millet", ig: 70 },
  { n: "Farine de noisette", ig: 20 },
  { n: "Farine de pois chiche", ig: 35 },
  { n: "Farine de quinoa", ig: 40 },
  { n: "Farine de riz blanc", ig: 95 },
  { n: "Farine de riz complète", ig: 75 },
  { n: "Farine de sarrasin", ig: 40 },
  { n: "Farine de seigle (complète)", ig: 45 },
  { n: "Farine de seigle (intégrale)", ig: 40 },
  { n: "Farine de soja", ig: 25 },
  { n: "Farine de souchet", ig: 35 },
  { n: "Farro", ig: 40 },
  { n: "Fenouil", ig: 15 },
  { n: "Figue sèche", ig: 40 },
  { n: "Figue; figue de barbarie (fraîche)", ig: 35 },
  { n: "Figues sèches", ig: 40 },
  { n: "Flageolets", ig: 25 },
  { n: "Flocons d'avoine (non cuite)", ig: 40 },
  { n: "Fraise (fruit frais)", ig: 25 },
  { n: "Framboise (fruit frais)", ig: 25 },
  { n: "Fromage blanc** non égoutté", ig: 30 },
  { n: "Fruit de la passion, maracudja, grenadille pourpre", ig: 30 },
  { n: "Fruit à pain, arbre à pain", ig: 65 },
  { n: "Fèves (crues)", ig: 40 },
  { n: "Fèves (cuites)", ig: 65 },
  { n: "Fécule de pomme de terre (amidon)", ig: 95 },
  { n: "Gaufre au sucre", ig: 75 },
  { n: "Gelée de coing (sans sucre)", ig: 40 },
  { n: "Gelée de coing (sucrée)", ig: 65 },
  { n: "Germe de blé", ig: 15 },
  { n: "Gingembre", ig: 15 },
  { n: "Glucose", ig: 100 },
  { n: "Gnocchi", ig: 70 },
  { n: "Graines de courges", ig: 25 },
  { n: "Graines germes", ig: 15 },
  { n: "Grenade (fruit frais)", ig: 35 },
  { n: "Groseille", ig: 25 },
  { n: "Groseille noire, cassis", ig: 15 },
  { n: "Groseille à maquereau", ig: 25 },
  { n: "Gâteau de riz", ig: 85 },
  { n: "Haricot adzuki", ig: 35 },
  { n: "Haricot borlotti", ig: 35 },
  { n: "Haricot coco", ig: 15 },
  { n: "Haricot mange-tout", ig: 15 },
  { n: "Haricot mungo (soja)", ig: 25 },
  { n: "Haricots blancs, cannellini", ig: 35 },
  { n: "Haricots noirs", ig: 35 },
  { n: "Haricots rouges", ig: 35 },
  { n: "Haricots rouges (boîte)", ig: 40 },
  { n: "Haricots verts", ig: 30 },
  { n: "Hummus, homus, humus", ig: 25 },
  { n: "Igname", ig: 65 },
  { n: "Kaki", ig: 50 },
  { n: "Kamut intégral", ig: 40 },
  { n: "Ketchup", ig: 55 },
  { n: "Kiwi", ig: 50 },
  { n: "Lactose", ig: 40 },
  { n: "Lait d'avoine (non cuite)", ig: 30 },
  { n: "Lait de coco", ig: 40 },
  { n: "Lait de riz", ig: 85 },
  { n: "Lait de soja", ig: 30 },
  { n: "Lait d’amande", ig: 30 },
  { n: "Lait frais/poudre*", ig: 30 },
  { n: "Lait** (écrémé ou non)", ig: 30 },
  { n: "Lasagnes (blé dur)", ig: 60 },
  { n: "Lasagnes (blé tendre)", ig: 75 },
  { n: "Lentilles brunes", ig: 30 },
  { n: "Lentilles jaunes", ig: 30 },
  { n: "Lentilles vertes", ig: 25 },
  { n: "Levure", ig: 35 },
  { n: "Levure de bière", ig: 35 },
  { n: "Lin  (graines de)", ig: 35 },
  { n: "Litchi (fruit frais)", ig: 50 },
  { n: "Lupin", ig: 15 },
  { n: "Macaronis (blé dur)", ig: 50 },
  { n: "Maizena (amidon de maïs)", ig: 85 },
  { n: "Maltodextrine", ig: 95 },
  { n: "Mandarines, clémentines", ig: 30 },
  { n: "Mangue (fruit frais)", ig: 50 },
  { n: "Mangue [Jus de] (sans sucre)", ig: 55 },
  { n: "Manioc (amer)", ig: 55 },
  { n: "Manioc (doux)", ig: 55 },
  { n: "Marmelade (sans sucre)", ig: 30 },
  { n: "Marmelade (sucrée)", ig: 65 },
  { n: "Mars®, Sneakers®, Nuts®, etc.", ig: 65 },
  { n: "Mayonnaise (industrielle, sucrée)", ig: 60 },
  { n: "Maïs ancestral (indien)", ig: 35 },
  { n: "Maïs courant en grains", ig: 65 },
  { n: "Melon", ig: 60 },
  { n: "Miel", ig: 60 },
  { n: "Mil, millet, sorgho", ig: 70 },
  { n: "Moutarde", ig: 35 },
  { n: "Moutarde (avec sucre ajouté)", ig: 55 },
  { n: "Muesli (avec sucre, miel…)", ig: 65 },
  { n: "Muesli (sans sucre)", ig: 50 },
  { n: "Mélasse", ig: 70 },
  { n: "Mûres", ig: 25 },
  { n: "Navet (cru)", ig: 30 },
  { n: "Navet (cuit)", ig: 85 },
  { n: "Noisettes", ig: 15 },
  { n: "Noix", ig: 15 },
  { n: "Noix de cajou", ig: 15 },
  { n: "Noix de coco", ig: 35 },
  { n: "Nouilles (blé tendre)", ig: 70 },
  { n: "Nouilles / vermicelle chinois (riz)", ig: 65 },
  { n: "Nutella", ig: 55 },
  { n: "Nèfle", ig: 55 },
  { n: "Oignons", ig: 15 },
  { n: "Olives", ig: 15 },
  { n: "Orange (fruit frais)", ig: 35 },
  { n: "Orange [Jus de] (sans sucre et pressé)", ig: 45 },
  { n: "Orge mondé", ig: 25 },
  { n: "Orge perlé", ig: 60 },
  { n: "Oseille", ig: 15 },
  { n: "Ovomaltine", ig: 60 },
  { n: "Pain 100% intégral au levain pur", ig: 40 },
  { n: "Pain Allemand (Pumpernickel)", ig: 40 },
  { n: "Pain au chocolat", ig: 65 },
  { n: "Pain au lait", ig: 60 },
  { n: "Pain au quinoa (environ 65 % de quinoa)", ig: 50 },
  { n: "Pain au seigle (30% de seigle)", ig: 65 },
  { n: "Pain azyme (farine blanche)", ig: 70 },
  { n: "Pain azyme (farine intégrale)", ig: 40 },
  { n: "Pain bis (au levain)", ig: 65 },
  { n: "Pain blanc sans gluten", ig: 90 },
  { n: "Pain complet", ig: 65 },
  { n: "Pain d'épeautre (farine intégrale)", ig: 45 },
  { n: "Pain de Kamut", ig: 45 },
  { n: "Pain de riz", ig: 70 },
  { n: "Pain Essène (de céréales germées)", ig: 35 },
  { n: "Pain grillé, farine intégrale sans sucre", ig: 45 },
  { n: "Pain hamburger", ig: 85 },
  { n: "Pain très blanc, pain de mie (type Harry's®)", ig: 85 },
  { n: "Pamplemousse (fruit frais)", ig: 30 },
  { n: "Pamplemousse [Jus de] (sans sucre)", ig: 45 },
  { n: "Panais", ig: 85 },
  { n: "Papaye (fruit frais)", ig: 55 },
  { n: "Pastèque", ig: 75 },
  { n: "Patate douce", ig: 50 },
  { n: "Pavot (graines de)", ig: 35 },
  { n: "Pepino, poire-melon", ig: 40 },
  { n: "Pesto", ig: 15 },
  { n: "Petits pois (boîte)", ig: 45 },
  { n: "Petits pois (frais)", ig: 35 },
  { n: "Physalis", ig: 15 },
  { n: "Pignon de pin", ig: 15 },
  { n: "Pilpil (de blé)", ig: 45 },
  { n: "Piment", ig: 15 },
  { n: "Pistache", ig: 15 },
  { n: "Pizza", ig: 60 },
  { n: "Poireaux", ig: 15 },
  { n: "Poires (fruits frais)", ig: 30 },
  { n: "Pois cassés", ig: 25 },
  { n: "Pois chiches", ig: 30 },
  { n: "Pois chiches (boîte)", ig: 35 },
  { n: "Pois mange tout", ig: 15 },
  { n: "Poivrons", ig: 15 },
  { n: "Polenta, semoule de maïs", ig: 70 },
  { n: "Pomme (compote)", ig: 35 },
  { n: "Pomme (fruit frais)", ig: 35 },
  { n: "Pomme [Jus de] (sans sucre)", ig: 50 },
  { n: "Pomme de terre au four", ig: 95 },
  { n: "Pomme de terre bouillies pelées", ig: 70 },
  { n: "Pomme de terre cuite dans sa peau (eau/vapeur)", ig: 65 },
  { n: "Pomme de terre en flocons (instantanée)", ig: 90 },
  { n: "Pomme de terre en purée", ig: 80 },
  { n: "Pomme de terre en salade", ig: 70 },
  { n: "Pomme de terre frites", ig: 95 },
  { n: "Pomme séchée", ig: 35 },
  { n: "Pop corn (sans sucre)", ig: 85 },
  { n: "Porridge, bouillie de flocons d'avoine", ig: 60 },
  { n: "Potiron", ig: 75 },
  { n: "Poudre chocolatée (sucrée)", ig: 60 },
  { n: "Poudre de caroube", ig: 15 },
  { n: "Pousse de bambou", ig: 20 },
  { n: "Prune (fruit frais)", ig: 35 },
  { n: "Pruneaux", ig: 40 },
  { n: "Pumpernickel standard", ig: 45 },
  { n: "Purée d'amandes blanches (sans sucre)", ig: 35 },
  { n: "Purée d'amandes complètes (sans sucre)", ig: 25 },
  { n: "Purée de cacahuètes (sans sucre)", ig: 25 },
  { n: "Purée de noisettes entières (sans sucre)", ig: 25 },
  { n: "Purée de sésame, tahin", ig: 40 },
  { n: "Pâtes complètes (blé entier) Al dente", ig: 40 },
  { n: "Pâtes complètes (blé entier) trop cuites", ig: 50 },
  { n: "Pâtes de riz intégral", ig: 65 },
  { n: "Pâtes non complètes Al dente", ig: 50 },
  { n: "Pâtes non complètes trop cuites", ig: 60 },
  { n: "Pêches (boîte, au sirop)", ig: 55 },
  { n: "Pêches (fruit frais)", ig: 35 },
  { n: "Quinoa", ig: 35 },
  { n: "Radis", ig: 15 },
  { n: "Raisin (fruit frais)", ig: 45 },
  { n: "Raisin [Jus de] (sans sucre)", ig: 55 },
  { n: "Raisins secs", ig: 65 },
  { n: "Ratatouille", ig: 20 },
  { n: "Raviolis (blé dur)", ig: 60 },
  { n: "Raviolis (blé tendre)", ig: 70 },
  { n: "Rhubarbe", ig: 15 },
  { n: "Risotto", ig: 70 },
  { n: "Riz a cuisson rapide (précuit)", ig: 85 },
  { n: "Riz au lait (sucré)", ig: 75 },
  { n: "Riz basmati complet", ig: 45 },
  { n: "Riz basmati long", ig: 50 },
  { n: "Riz blanc standard", ig: 70 },
  { n: "Riz complet brun", ig: 50 },
  { n: "Riz de Camargue", ig: 60 },
  { n: "Riz glutineux, riz agglutinant", ig: 90 },
  { n: "Riz long", ig: 60 },
  { n: "Riz parfumé (jasmin...)", ig: 60 },
  { n: "Riz rouge", ig: 55 },
  { n: "Riz sauvage", ig: 35 },
  { n: "Riz soufflé, galettes de riz", ig: 85 },
  { n: "Rutabaga", ig: 70 },
  { n: "Sablé (farine intégrale, sans sucre)", ig: 40 },
  { n: "Salade (laitue, scarole, frisée, mâche, etc.)", ig: 15 },
  { n: "Salsifis", ig: 30 },
  { n: "Sarrasin, blé noir (intégral; farine ou pain)", ig: 40 },
  { n: "Sauce tamari (sans sucre ni édulcorants)", ig: 20 },
  { n: "Sauce tomate, coulis de tomate (avec sucre)", ig: 45 },
  { n: "Sauce tomate, coulis de tomate (sans sucre)", ig: 35 },
  { n: "Seigle (intégral; farine ou pain)", ig: 45 },
  { n: "Semoule de blé dur", ig: 60 },
  { n: "Sirop de blé, sirop de riz", ig: 100 },
  { n: "Sirop de chicorée", ig: 55 },
  { n: "Sirop de glucose", ig: 100 },
  { n: "Sirop de maïs", ig: 115 },
  { n: "Sirop d’érable", ig: 65 },
  { n: "Soja (graines/noix)", ig: 15 },
  { n: "Soja cuisine", ig: 20 },
  { n: "Son (de blé, d'avoine...)", ig: 15 },
  { n: "Sorbet (sans sucre)", ig: 40 },
  { n: "Sorbet (sucré)", ig: 65 },
  { n: "Spaghetti al dente (cuits 5 minutes)", ig: 40 },
  { n: "Spaghetti blancs bien cuits", ig: 55 },
  { n: "Special K®", ig: 70 },
  { n: "Sucre blanc (saccharose)", ig: 70 },
  { n: "Sucre roux / complet / intégral", ig: 70 },
  { n: "Surimi", ig: 50 },
  { n: "Sushi", ig: 55 },
  { n: "Sésame (graines de)", ig: 35 },
  { n: "Tacos", ig: 70 },
  { n: "Tagliatelles (bien cuites)", ig: 55 },
  { n: "Tamarin (doux)", ig: 65 },
  { n: "Tapioca", ig: 85 },
  { n: "Tempeh", ig: 15 },
  { n: "Tofu (soja)", ig: 15 },
  { n: "Tomate", ig: 30 },
  { n: "Tomate [Jus de]", ig: 35 },
  { n: "Tomate séchée", ig: 35 },
  { n: "Topinambour, artichaut de Jérusalem", ig: 50 },
  { n: "Tournesol (graines)", ig: 35 },
  { n: "Vermicelle de blé dur", ig: 35 },
  { n: "Vermicelle de soja", ig: 30 },
  { n: "Wasa fibre (24%)", ig: 35 },
  { n: "Wasa léger", ig: 50 },
  { n: "Yaourt au soja (aromatisé)", ig: 35 },
  { n: "Yaourt au soja (nature)", ig: 20 },
  { n: "Yaourt, yoghourt, yogourt (nature)*", ig: 35 },
];

export function giCategory(ig) {
  if (ig < 40) return { key: 'low',  label: 'IG bas',   color: '#1fb86b' };
  if (ig < 60) return { key: 'med',  label: 'IG moyen', color: '#f5a623' };
  return { key: 'high', label: 'IG élevé', color: '#ff5a5a' };
}

// Recherche simple (insensible aux accents/casse).
function norm(s) {
  return s.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
}
export function searchGI(query, limit = 40) {
  const q = norm(query.trim());
  if (!q) return GI_FOODS.slice(0, limit);
  return GI_FOODS
    .filter((f) => norm(f.n).includes(q))
    .sort((a, b) => norm(a.n).indexOf(q) - norm(b.n).indexOf(q))
    .slice(0, limit);
}
